version: "3"
services:
  web: 
    build: ./stat-dash-web
    container_name: stat-dash-web
    ports: 
      - 3000:3000
      
  back:
    build: ./stat-dash-back
    container_name: stat-dash-back
    ports:
      - 4000:4000

  postgres:
    build: ./stat-dash-postgres
    restart: always
    container_name: stat-dash-postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB_LIST: stat_dash
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8090:8080
    environment:
      ADMINER_DEFAULT_SERVER: postgres

volumes:
  pgdata:

